package com.philipnerubenko.spring.mvc.rest.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Represents an employee entity mapped to the "employees" table in the database.
 * This class defines the structure of an employee record with fields for ID, name,
 * surname, department, and salary, along with JPA annotations for database mapping.
 */
@Entity
@Table(name = "employees")
public class Employee {
  /**
   * Unique identifier for the employee, automatically generated by the database.
   * <p>
   * Annotation: {@literal @}Id, {@literal @}GeneratedValue(strategy = GenerationType.IDENTITY),
   * {@literal @}Column(name = "id")
   */
  @Id @GeneratedValue(strategy = GenerationType.IDENTITY) @Column(name = "id") private int id;

  /**
   * Name of the employee.
   * <p>
   * Annotation: {@literal @}Column(name = "name")
   */
  @Column(name = "name") private String name;

  /**
   * Surname of the employee.
   * <p>
   * Annotation: {@literal @}Column(name = "surname")
   */
  @Column(name = "surname") private String surname;

  /**
   * Department where the employee works.
   * <p>
   * Annotation: {@literal @}Column(name = "department")
   */
  @Column(name = "department") private String department;

  /**
   * Salary of the employee.
   * <p>
   * Annotation: {@literal @}Column(name = "salary")
   */
  @Column(name = "salary") private int salary;

  /**
   * Default constructor required by JPA for entity instantiation.
   * Initializes an empty Employee object.
   */
  public Employee() {}

  /**
   * Constructs a new Employee with specified attributes.
   *
   * @param name       the employee's name
   * @param surname    the employee's surname
   * @param department the employee's department
   * @param salary     the employee's salary
   */
  public Employee(String name, String surname, String department, int salary) {
    this.name = name;
    this.surname = surname;
    this.department = department;
    this.salary = salary;
  }

  /**
   * Returns the unique identifier of the employee.
   *
   * @return the employee ID
   */
  public int getId() {
    return id;
  }

  /**
   * Sets the unique identifier of the employee.
   *
   * @param id the new ID value
   */
  public void setId(int id) {
    this.id = id;
  }

  /**
   * Returns the employee's name.
   *
   * @return the name
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the employee's name.
   *
   * @param name the new name value
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Returns the employee's surname.
   *
   * @return the surname
   */
  public String getSurname() {
    return surname;
  }

  /**
   * Sets the employee's surname.
   *
   * @param surname the new surname value
   */
  public void setSurname(String surname) {
    this.surname = surname;
  }

  /**
   * Returns the employee's department.
   *
   * @return the department
   */
  public String getDepartment() {
    return department;
  }

  /**
   * Sets the employee's department.
   *
   * @param department the new department value
   */
  public void setDepartment(String department) {
    this.department = department;
  }

  /**
   * Returns the employee's salary.
   *
   * @return the salary
   */
  public int getSalary() {
    return salary;
  }

  /**
   * Sets the employee's salary.
   *
   * @param salary the new salary value
   */
  public void setSalary(int salary) {
    this.salary = salary;
  }
}
